import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { GetServerSideProps } from 'next'
import Card from '../components/Card'
import Pagination from '@/components/Pagination'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

// const inter = Inter({ subsets: ['latin'] })



export default function Home({characters, infos}:any) {
  const [currentPage, setCurrentPage] = useState(1)
  const router = useRouter()

  const buttonHandler = (e:any) => router.push('/?page=' + e.target.value)

  return (
    <>
      <Head>
        <title>Rick & Morty | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input className={styles.searchBox} type="text" placeholder='Search for characters here..........'/>
        <div className={styles.flexContainer}>
        {characters.map(
                (character:any)=>{
                  return <Link href={String(character.id)} ><Card 
                  key={character.id} 
                  name={character.name} 
                  species={character.species}
                  type={character.type}
                  gender={character.gender}
                  image={character.image}/></Link>
                  }
                  )}
        </div>
        <div>
          <Pagination totalPage={infos.pages} currentPage={currentPage} buttonHandler={buttonHandler}/>
      </div>
      </main>
      
    </>
  )
}



export const getServerSideProps : GetServerSideProps = async (context:any) => {
  const page = context.query.page
  const url = 'https://rickandmortyapi.com/api/character/?page=' + String(page)
  // const response = await fetch(url + '?' + new URLSearchParams({'page': curre}))
  const response = await fetch(url)
  const data = await response.json()
  // console.log(context.query.page)
  return {
    props : {
      characters : data.results,
      infos: data.info
    }
  }
}

